# Note: If you update this, make sure to update tox.ini, too.
dist: xenial
language: python
cache:
  directories:
  - "~/.cache/pip"
arch:
    - amd64
    - arm64
python:
  - "3.8"
  
install:
  - pip install -U pip setuptools>=18.5
  - pip install -r requirements-dev.txt
script:
  - ./scripts/run_tests.sh $MODE
